version: '3'
services:
  web:
    build: .
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - /etc/ssh:/etc/ssh
    ports:
      - "3000:3000"
    links:
      - redis
  sidekiq:
    restart: always
    volumes:
      - .:/app
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    links:
      - redis
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes
volumes:
  redis-data:
